# Generated by Django 5.2.16 on 2026-07-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'Online Payment'), ('pod', 'Pay on Delivery')], default='online', max_length=20),
        ),
    ]
