# Generated by Django 5.2.16 on 2026-07-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
