# Generated by Django 5.2.16 on 2026-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_ordergroup_booking_order_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_noted',
            field=models.BooleanField(default=False),
        ),
    ]
