# Generated by Django 5.2.16 on 2026-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_ordergroup_aadhar_number_ordergroup_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='aadhar_photo',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_photos/'),
        ),
    ]
