# Generated by Django 5.2.16 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
