# Generated by Django 5.2.16 on 2026-07-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='24, Jawahar St, opp.to municipal middle school, Adivaram, South Anna Nagar, Palani, Tamil Nadu 624601')),
                ('maps_url', models.URLField(default='https://www.google.com/maps/search/?api=1&query=24,+Jawahar+St,+opp.to+municipal+middle+school,+Adivaram,+South+Anna+Nagar,+Palani,+Tamil+Nadu+624601')),
                ('phone_number', models.CharField(default='+91 7010276853', max_length=20)),
            ],
        ),
    ]
