# Generated by Django 5.2.16 on 2026-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='cancellation_policy',
            field=models.TextField(blank=True, default='Cancellation and refund policy goes here.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='privacy_policy',
            field=models.TextField(blank=True, default='Privacy policy goes here.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_conditions',
            field=models.TextField(blank=True, default='Terms and conditions go here.'),
        ),
    ]
